"""added num_id and title col to line_messages

Revision ID: 4173f3b611ef
Revises: 974043b41734
Create Date: 2022-01-16 20:40:29.018439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4173f3b611ef'
down_revision = '974043b41734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_messages', sa.Column('num_id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False))
    op.add_column('line_messages', sa.Column('title', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_messages', 'title')
    op.drop_column('line_messages', 'num_id')
    # ### end Alembic commands ###
