"""Added LineWebhooks table

Revision ID: adc3eebd676c
Revises: adcb3e9876ca
Create Date: 2021-12-20 14:05:20.218436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc3eebd676c'
down_revision = 'adcb3e9876ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=14), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'admins', ['username'])
    op.create_unique_constraint(None, 'admins', ['password'])
    op.drop_constraint('admins_member_id_fkey', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'members', ['member_id'], ['id'])
    op.drop_constraint('line_messages_created_by_fkey', 'line_messages', type_='foreignkey')
    op.create_foreign_key(None, 'line_messages', 'members', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_messages', type_='foreignkey')
    op.create_foreign_key('line_messages_created_by_fkey', 'line_messages', 'members', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_member_id_fkey', 'admins', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_table('line_webhooks')
    # ### end Alembic commands ###
