"""adjusted_ondelete_linemessages_admins

Revision ID: b8b82aa4122b
Revises: adc3eebd676c
Create Date: 2021-12-20 14:57:20.349982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b82aa4122b'
down_revision = 'adc3eebd676c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_member_id_fkey', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('line_messages_created_by_fkey', 'line_messages', type_='foreignkey')
    op.create_foreign_key(None, 'line_messages', 'members', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_messages', type_='foreignkey')
    op.create_foreign_key('line_messages_created_by_fkey', 'line_messages', 'members', ['created_by'], ['id'])
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_member_id_fkey', 'admins', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###
