"""added linewebhooks, minor changes to previous tables

Revision ID: cb43b2df8ebe
Revises: adcb3e9876ca
Create Date: 2021-12-21 13:50:16.429403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb43b2df8ebe'
down_revision = 'adcb3e9876ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=14), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('groupId', sa.String(length=40), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'admins', ['username'])
    op.create_unique_constraint(None, 'admins', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_table('line_webhooks')
    # ### end Alembic commands ###
